### PR TITLE
Add Macedonian locale

### PR DESCRIPTION
**Pull request by blzr**

### CODE REVIEW

**Comment by malakudi** [comment]
There is no "Macedonian" locale, there is "Northern Macedonian" locale.

**Comment by persianpros** [comment]
But "mk_MK" is valid with "Macedonian (North Macedonia)" name so it's correct.

**Comment by malakudi** [comment]
> But "mk_MK" is valid with "Macedonian (North Macedonia)" name so it's correct.

No, there is no "Macedonian". The nationality is "North Macedonian" and the citizenship is "Macedonian/Citizen of the Republic of North Macedonia". This was aggreed between the two countries on the Prespa Agreement.

**Comment by blzr** [comment]
not sure where the problem is - in commit's subject? or in the (official and commonly used) glibc locale file?
"Macedonian language locale" is in a locale body, would this be more politically correct?
If not, feel free to correct it like you want...

**Comment by malakudi** [comment]
That file contains information that is in violation with the Prespa Aggreement. There is no "Macedonia" territory. The file should be updated.

**Comment by blzr** [comment]
well, like I wrote: "If not, feel free to correct it like you want..."
no idea what's Prespa agreement, and how it's related to gnu libraries, I'm really not into politics in hobby/opensource, however if it's such a big deal, I can close this PR and call it a day

**Comment by persianpros** [comment]
I think this PR should be merged then a new PR from @malakudi update it so we understand the difference.

**Comment by WanWizard** [comment]
See https://en.wikipedia.org/wiki/Macedonia_naming_dispute. I can imagine the people involved have a strong opinion about this, given its history.

Having said that, we use the standard linux glibc locale (https://sourceware.org/git/?p=glibc.git;a=blob;f=localedata/locales/mk_MK;h=87bae1dc7ce557371d21ea4e4eec010b6c043a4c;hb=HEAD) which still doesn't mention "North", so in that respect it would be better to have this changed upstream, instead of deviate from gnu glibc.

**Comment by malakudi** [comment]
> See https://en.wikipedia.org/wiki/Macedonia_naming_dispute. I can imagine the people involved have a strong opinion about this, given its history.
> 
> Having said that, we use the standard linux glibc locale (https://sourceware.org/git/?p=glibc.git;a=blob;f=localedata/locales/mk_MK;h=87bae1dc7ce557371d21ea4e4eec010b6c043a4c;hb=HEAD) which still doesn't mention "North", so in that respect it would be better to have this changed upstream, instead of deviate from gnu glibc.

My opinion is quite different and against what was signed in the Prespa Agreement. But since it was signed, both sides should respect it. Language was agreed to be called "Macedonian", but with a note that it belongs to the group of "South Slavic" languages. Territory is now called "North Macedonia" and citizenship is called "Macedonian/Citizen of the republic of North Macedonia". So the file should be fixed to include above information.

I understand this should be fixed upstream.

**Comment by blzr** [comment]
ok, so I'm really not sure what to do now?
new PR with changed commit subject to something like below will be acceptable for the moment?
```
Date: Sat, 20 Feb 2021 09:01:36 +0100
Subject: [PATCH] Add Macedonian language locale for North Macedonia

Have been used standard linux glibc locale:
https://sourceware.org/git/?p=glibc.git;a=blob;f=localedata/locales/mk_MK;h=87bae1dc7ce557371d21ea4e4eec010b6c043a4c;hb=HEAD
```
or just close it for now, and wait until mk_MK is changed upstream?

**Comment by blzr** [comment]
I'll provide new PR with more detailed / clearer description soon, so that is acceptable for all for now (?)
We''ll see...

**Pull request closed without merging**
